# Generated by Django 4.1.7 on 2023-03-09 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="mpesa_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
