# Generated by Django 4.1.7 on 2023-03-09 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_rename_donation_donation_amount_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="quantity",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
